using System.Text.RegularExpressions;
using JetBrains.Annotations;
using mvdmio.Database.PgSQL.Migrations.Models;

namespace mvdmio.Database.PgSQL.Migrations;

/// <summary>
///    Parses schema files generated by <see cref="Connectors.Schema.SchemaExtractor"/> to extract
///    migration version information from the header comments.
/// </summary>
[PublicAPI]
public static partial class SchemaFileParser
{
   /// <summary>
   ///    The regex pattern used to extract migration version from the schema file header.
   ///    Matches lines like: "-- Migration version: 202602161430 (AddUsersTable)"
   /// </summary>
   [GeneratedRegex(@"^--\s*Migration version:\s*(\d+)\s*\(([^)]+)\)\s*$", RegexOptions.Multiline)]
   private static partial Regex MigrationVersionRegex();

   /// <summary>
   ///    Parses the migration version from a schema file's content.
   /// </summary>
   /// <param name="schemaFileContent">The full content of the schema file.</param>
   /// <returns>
   ///    A <see cref="SchemaFileMigrationInfo"/> containing the identifier and name of the migration
   ///    that was current when the schema file was generated, or null if no migration version could be found
   ///    (e.g., the schema file was generated from an empty database or has an invalid format).
   /// </returns>
   public static SchemaFileMigrationInfo? ParseMigrationVersion(string schemaFileContent)
   {
      var match = MigrationVersionRegex().Match(schemaFileContent);

      if (!match.Success)
         return null;

      if (!long.TryParse(match.Groups[1].Value, out var identifier))
         return null;

      var name = match.Groups[2].Value.Trim();

      if (string.IsNullOrEmpty(name) || name == "none")
         return null;

      return new SchemaFileMigrationInfo(identifier, name);
   }

   /// <summary>
   ///    Parses the migration version from a schema file at the specified path.
   /// </summary>
   /// <param name="schemaFilePath">The path to the schema file.</param>
   /// <returns>
   ///    A <see cref="SchemaFileMigrationInfo"/> containing the identifier and name of the migration
   ///    that was current when the schema file was generated, or null if no migration version could be found.
   /// </returns>
   /// <exception cref="FileNotFoundException">Thrown if the schema file does not exist.</exception>
   public static SchemaFileMigrationInfo? ParseMigrationVersionFromFile(string schemaFilePath)
   {
      if (!File.Exists(schemaFilePath))
         throw new FileNotFoundException($"Schema file not found: {schemaFilePath}", schemaFilePath);

      var content = File.ReadAllText(schemaFilePath);
      return ParseMigrationVersion(content);
   }

   /// <summary>
   ///    Asynchronously parses the migration version from a schema file at the specified path.
   /// </summary>
   /// <param name="schemaFilePath">The path to the schema file.</param>
   /// <param name="cancellationToken">A cancellation token.</param>
   /// <returns>
   ///    A <see cref="SchemaFileMigrationInfo"/> containing the identifier and name of the migration
   ///    that was current when the schema file was generated, or null if no migration version could be found.
   /// </returns>
   /// <exception cref="FileNotFoundException">Thrown if the schema file does not exist.</exception>
   public static async Task<SchemaFileMigrationInfo?> ParseMigrationVersionFromFileAsync(string schemaFilePath, CancellationToken cancellationToken = default)
   {
      if (!File.Exists(schemaFilePath))
         throw new FileNotFoundException($"Schema file not found: {schemaFilePath}", schemaFilePath);

      var content = await File.ReadAllTextAsync(schemaFilePath, cancellationToken);
      return ParseMigrationVersion(content);
   }
}
