using AwesomeAssertions;
using mvdmio.Database.PgSQL.Tests.Integration.Fixture;
using mvdmio.Database.PgSQL.Tool.Configuration;
using mvdmio.Database.PgSQL.Tool.Copy;
using Npgsql;

namespace mvdmio.Database.PgSQL.Tests.Integration.Tool;

/// <summary>
///    End-to-end integration tests for the <c>db copy</c> command via <see cref="CopyHandler"/>.
///    Uses two databases on the shared PostgreSQL container as source and destination.
/// </summary>
public class CopyHandlerIntegrationTests : IAsyncLifetime
{
   private readonly TestFixture _fixture;
   private string _sourceDbName = null!;
   private string _destDbName = null!;
   private string _sourceConnectionString = null!;
   private string _destConnectionString = null!;

   protected static CancellationToken CancellationToken => TestContext.Current.CancellationToken;

   public CopyHandlerIntegrationTests(TestFixture fixture)
   {
      _fixture = fixture;
   }

   public async ValueTask InitializeAsync()
   {
      var unique = Guid.NewGuid().ToString("N")[..12];
      _sourceDbName = $"copyend_src_{unique}";
      _destDbName = $"copyend_dst_{unique}";
      _sourceConnectionString = await CreateDatabaseAsync(_sourceDbName);
      _destConnectionString = await CreateDatabaseAsync(_destDbName);
   }

   public async ValueTask DisposeAsync()
   {
      await DropDatabaseAsync(_sourceDbName);
      await DropDatabaseAsync(_destDbName);
   }

   [Fact]
   public async Task HandleAsync_WithSeededSource_TruncatesDestinationAndCopiesAllData()
   {
      const string ddl = """
         CREATE SCHEMA app;
         CREATE TABLE app.users (
            id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name  text NOT NULL,
            email text
         );
         CREATE TABLE app.orders (
            id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id   bigint NOT NULL REFERENCES app.users(id),
            amount    numeric(10,2) NOT NULL,
            placed_at timestamptz NOT NULL DEFAULT now()
         );
         """;

      await ExecuteAsync(_sourceConnectionString, ddl);
      await ExecuteAsync(_destConnectionString, ddl);

      // Seed source.
      await using (var src = new DatabaseConnection(_sourceConnectionString))
      {
         await src.Dapper.ExecuteAsync("""
            INSERT INTO app.users (id, name, email) VALUES (10, 'Alice', 'a@example.com'), (11, 'Bob', NULL);
            INSERT INTO app.orders (id, user_id, amount) VALUES (100, 10, 9.99), (101, 11, 5.50);
            -- bump sequences past the inserted ids
            SELECT setval(pg_get_serial_sequence('app.users','id'), 11);
            SELECT setval(pg_get_serial_sequence('app.orders','id'), 101);
            """, ct: CancellationToken);
      }

      // Pre-populate destination with garbage that must be wiped.
      await using (var dst = new DatabaseConnection(_destConnectionString))
      {
         await dst.Dapper.ExecuteAsync("""
            INSERT INTO app.users (name) VALUES ('Stale');
            """, ct: CancellationToken);
      }

      var config = new ToolConfiguration
      {
         BasePath = Path.GetTempPath(),
         ConnectionStrings = new Dictionary<string, string>
         {
            ["src"] = _sourceConnectionString,
            ["dst"] = _destConnectionString
         },
         Schemas = ["app"]
      };

      var reporter = new RecordingReporter();
      var handler = new CopyHandler(new CopyService(), reporter);

      await handler.HandleAsync(config, "src", "dst", null, null, CancellationToken);

      reporter.Errors.Should().BeEmpty();

      await using var verify = new DatabaseConnection(_destConnectionString);
      var users = (await verify.Dapper.QueryAsync<UserRow>("SELECT id, name, email FROM app.users ORDER BY id", ct: CancellationToken)).ToArray();
      users.Should().HaveCount(2);
      users[0].Id.Should().Be(10);
      users[0].Name.Should().Be("Alice");
      users[1].Id.Should().Be(11);

      var orders = (await verify.Dapper.QueryAsync<OrderRow>("SELECT id, user_id, amount FROM app.orders ORDER BY id", ct: CancellationToken)).ToArray();
      orders.Should().HaveCount(2);
      orders[0].UserId.Should().Be(10);
      orders[0].Amount.Should().Be(9.99m);

      // After copy, sequences should be advanced past the max id so new inserts work.
      var newUserId = await verify.Dapper.QuerySingleAsync<long>(
         "INSERT INTO app.users (name) VALUES ('Carol') RETURNING id",
         ct: CancellationToken
      );
      newUserId.Should().BeGreaterThan(11);
   }

   [Fact]
   public async Task HandleAsync_WithMissingTableInDestination_ReportsErrorAndDoesNotCopy()
   {
      await ExecuteAsync(_sourceConnectionString, """
         CREATE TABLE public.users (id integer PRIMARY KEY);
         CREATE TABLE public.orders (id integer PRIMARY KEY);
         """);
      await ExecuteAsync(_destConnectionString, "CREATE TABLE public.users (id integer PRIMARY KEY);");

      var config = new ToolConfiguration
      {
         BasePath = Path.GetTempPath(),
         ConnectionStrings = new Dictionary<string, string>
         {
            ["src"] = _sourceConnectionString,
            ["dst"] = _destConnectionString
         }
      };

      var reporter = new RecordingReporter();
      var handler = new CopyHandler(new CopyService(), reporter);

      await handler.HandleAsync(config, "src", "dst", null, null, CancellationToken);

      reporter.Errors.Should().ContainSingle().Which.Should().Contain("public.orders");
   }

   [Fact]
   public async Task HandleAsync_WithExcludedTable_SkipsThatTable()
   {
      const string ddl = """
         CREATE TABLE public.keep_me (id integer PRIMARY KEY, value text);
         CREATE TABLE public.skip_me (id integer PRIMARY KEY, value text);
         """;

      await ExecuteAsync(_sourceConnectionString, ddl);
      await ExecuteAsync(_destConnectionString, ddl);

      await using (var src = new DatabaseConnection(_sourceConnectionString))
      {
         await src.Dapper.ExecuteAsync("""
            INSERT INTO public.keep_me VALUES (1, 'kept');
            INSERT INTO public.skip_me VALUES (1, 'skipped');
            """, ct: CancellationToken);
      }

      await using (var dst = new DatabaseConnection(_destConnectionString))
      {
         await dst.Dapper.ExecuteAsync("INSERT INTO public.skip_me VALUES (99, 'preserved');", ct: CancellationToken);
      }

      var config = new ToolConfiguration
      {
         BasePath = Path.GetTempPath(),
         ConnectionStrings = new Dictionary<string, string>
         {
            ["src"] = _sourceConnectionString,
            ["dst"] = _destConnectionString
         }
      };

      var handler = new CopyHandler(new CopyService(), new RecordingReporter());
      await handler.HandleAsync(config, "src", "dst", null, ["public.skip_me"], CancellationToken);

      await using var verify = new DatabaseConnection(_destConnectionString);
      var keep = (await verify.Dapper.QueryAsync<int>("SELECT id FROM public.keep_me ORDER BY id", ct: CancellationToken)).ToArray();
      keep.Should().BeEquivalentTo([1]);

      var skip = (await verify.Dapper.QueryAsync<int>("SELECT id FROM public.skip_me ORDER BY id", ct: CancellationToken)).ToArray();
      skip.Should().BeEquivalentTo([99]); // untouched
   }

   private async Task<string> CreateDatabaseAsync(string dbName)
   {
      var adminCs = _fixture.DbContainer.GetConnectionString();
      await using var admin = new NpgsqlConnection(adminCs);
      await admin.OpenAsync(CancellationToken);
      await using var cmd = admin.CreateCommand();
      cmd.CommandText = $"CREATE DATABASE \"{dbName}\"";
      await cmd.ExecuteNonQueryAsync(CancellationToken);

      return new NpgsqlConnectionStringBuilder(adminCs) { Database = dbName }.ConnectionString;
   }

   private async Task DropDatabaseAsync(string dbName)
   {
      var adminCs = _fixture.DbContainer.GetConnectionString();
      await using var admin = new NpgsqlConnection(adminCs);
      await admin.OpenAsync();
      await using var cmd = admin.CreateCommand();
      cmd.CommandText = $"DROP DATABASE IF EXISTS \"{dbName}\" WITH (FORCE)";
      await cmd.ExecuteNonQueryAsync();
   }

   private async Task ExecuteAsync(string connectionString, string sql)
   {
      await using var db = new DatabaseConnection(connectionString);
      await db.Dapper.ExecuteAsync(sql, ct: CancellationToken);
   }

   private sealed record UserRow
   {
      public long Id { get; init; }
      public string Name { get; init; } = "";
      public string? Email { get; init; }
   }

   private sealed record OrderRow
   {
      public long Id { get; init; }
      public long UserId { get; init; }
      public decimal Amount { get; init; }
   }

   private sealed class RecordingReporter : ICopyReporter
   {
      public List<string> Infos { get; } = [];
      public List<string> Warnings { get; } = [];
      public List<string> Errors { get; } = [];

      public void WriteInfo(string message) => Infos.Add(message);
      public void WriteWarning(string message) => Warnings.Add(message);
      public void WriteError(string message) => Errors.Add(message);
   }
}
