using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace mvdmio.Database.PgSQL.Tool.Configuration;

/// <summary>
///    Configuration model for the migration tool, loaded from .mvdmio-migrations.yml.
/// </summary>
public sealed class ToolConfiguration
{
   /// <summary>
   ///    The name of the configuration file.
   /// </summary>
   public const string CONFIG_FILE_NAME = ".mvdmio-migrations.yml";

   /// <summary>
   ///    Path to the project containing migrations, relative to the config file location.
   /// </summary>
   public string Project { get; set; } = ".";

   /// <summary>
   ///    Output directory for new migration files, relative to the config file location.
   /// </summary>
   public string MigrationsDirectory { get; set; } = "Migrations";

   /// <summary>
   ///    Output directory for schema files generated by the pull command, relative to the config file location.
   /// </summary>
   public string SchemasDirectory { get; set; } = "Schemas";

   /// <summary>
   ///    Named connection strings, keyed by environment name (e.g. "local", "acc", "prod").
   ///    When no --environment flag is passed, the first entry is used as the default.
   /// </summary>
   public Dictionary<string, string>? ConnectionStrings { get; set; }

   /// <summary>
   ///    Optional list of PostgreSQL schemas to export. When omitted or empty, all user schemas are exported.
   /// </summary>
   public List<string>? Schemas { get; set; }

   /// <summary>
   ///    The directory containing the config file. Used to resolve relative paths.
   ///    Not serialized from YAML.
   /// </summary>
   [YamlIgnore]
   public string BasePath { get; set; } = Directory.GetCurrentDirectory();

   /// <summary>
   ///    Saves the configuration to a .mvdmio-migrations.yml file in the specified directory.
   /// </summary>
   /// <param name="directory">The directory to write the config file to.</param>
   public void Save(string directory)
   {
      Schemas = NormalizeSchemas(Schemas);

      var serializer = new SerializerBuilder()
         .WithNamingConvention(CamelCaseNamingConvention.Instance)
         .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull | DefaultValuesHandling.OmitDefaults)
         .Build();

      var yaml = serializer.Serialize(this);
      var filePath = Path.Combine(directory, CONFIG_FILE_NAME);
      File.WriteAllText(filePath, yaml);
   }

   private static List<string>? NormalizeSchemas(List<string>? schemas)
   {
      if (schemas is null)
         return null;

      var normalized = schemas
         .Select(schema => schema.Trim())
         .Where(schema => schema.Length > 0)
         .Distinct(StringComparer.Ordinal)
         .ToList();

      return normalized.Count > 0 ? normalized : null;
   }
}
