//HintName: TestDbTable_Columns.g.cs
using System;
using mvdmio.Database.PgSQL;

namespace mvdmio.Database.PgSQL.Tests.Unit
{
    /// <auto-generated />
    public partial class TestDbTable : DbRecord
    {
       public override object? GetValue(string column)
       {
            return column switch
            {
               "id" => Id,
               "first_name" => FirstName,
               "last_name" => LastName,
               "email" => Email,
               _ => throw new ArgumentException($"Column '{column}' not found in '{nameof(TestDbTable)}'")
            };
       }
    }
}
