//HintName: TestDbTable_Columns.g.cs
using System;
using mvdmio.Database.PgSQL;

namespace mvdmio.Database.PgSQL.Tests.Unit
{
    /// <auto-generated />
    public class TestDbTableDbTable : DbTable<TestDbTable>
    {
       private readonly DatabaseConnection _db;
    
       protected internal override string TableName => "test_table";
       protected internal override string Schema => "test_schema";
       protected internal override string[] Columns => [ "id", "first_name", "last_name", "email" ];
       protected internal override string[] PrimaryKeyColumns => [ "id" ];
       protected internal override string[] GeneratedColumns => [  ];
       
       /// <summary>
       ///   Constructor.
       /// </summary>
       public TestDbTableDbTable(DatabaseConnection db)
         : base(db)
       {
         _db = db;
       }
    }
}
