//HintName: TestDbTable_Columns.g.cs
using System;

namespace mvdmio.Database.PgSQL.Tests.Unit
{
    /// <auto-generated />
    public partial class TestDbTable
    {
        internal static string[] ColumnNames { get; } = new[] { "id", "first_name", "last_name", "email" };
    }
}
