//HintName: TestDbTable_Columns.g.cs
using System;
using mvdmio.Database.PgSQL;

namespace mvdmio.Database.PgSQL.Tests.Unit
{
    /// <auto-generated />
    public partial class TestDbTable : DbTable
    {
       public override string TableName => "test_table";
       public override string Schema => "test_schema";
       public override string[] Columns => new[] { "id", "first_name", "last_name", "email" };
       public override string[] PrimaryKeyColumns => new[] { "id" };
    }
}
